trigger:
- main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'
  versionSuffix: '1.0.$(Build.BuildId)' 

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: 'stipanso-test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    configuration: 'Release'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'versionSuffix'

- task: DotNetCoreCLI@2
  displayName: 'Push NuGet package'
  inputs:
    command: 'push'
    publishVstsFeed: 'stipanso-test'
    arguments: '--skip-duplicate'
